dist: xenial
language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6
- 3.7
- 3.8-dev
- pypy2.7-6.0
- pypy3.5

env:
 - PYTHONWARNINGS='ignore::DeprecationWarning' # Until python_toolbox is fixed

install:
- pip install -r test_requirements.txt
script:
- pytest
